modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/coderslabs/Forge-Starter-Mod/issues"
[[mods]]
modId="tutorialforge"
version="1.0.0"
displayName="Forge Starter Mod"
logoFile="forge.png"
credits="JustinPlayzz, TurtyWurty, TechnoVision, EltrutLikes"
authors="Team Frost"
description='''
Starter Mod, I have used some of TechnoVision textures too :cojo:!
'''

[[dependencies.tutorialforge]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tutorialforge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5, 1.17)"
    ordering="NONE"
    side="BOTH"
